### ISSUE TITLE
Release branch linux driver doesn't build on RockyLinux 9.3

### ISSUE THREAD

**Issue by stefd** [aja-video/libajantv2#4]
When building the linux driver from the "release" branch on RL 9.3, we get this:

> [100%] Building Linux driver
> linux distro: rocky
> linux distro flags: -DDISTRO_TYPE=rocky -DDISTRO_IS_RHEL_LIKE=1 -DDISTRO_MAJ_VERSION=9 -DDISTRO_MIN_VERSION=3 -DDISTRO_KERNEL_PKG_MAJ=362 -DDISTRO_KERNEL_PKG_MIN=8 -DDISTRO_KERNEL_PKG_PNT=1
> lib: lib
> /root/Downloads/aja17/libajantv2-release/driver/linux/ntv2driver.c: In function ‘aja_ntv2_module_init’:
> /root/Downloads/aja17/libajantv2-release/driver/linux/ntv2driver.c:2991:32: error: assignment to ‘int (*)(const struct device *, struct kobj_uevent_env *)’ from incompatible pointer type ‘int (*)(struct device *, struct kobj_uevent_env *)’ [-Werror=incompatible-pointer-types]
>  2991 |         ntv2_class->dev_uevent = aja_ntv2_dev_uevent;

I see there is a fix for this (file driver/linux/buildenv.h) in the 17_0 and main branches (which compile properly).

**Comment by janbrothanek** [comment]
Hi, as we're having the same issue, can we expect the **ntv2_17_0** to be merged to **release** branch soon? I'm just wondering if we should wait or modify our workflow to cherry-pick the respective commits.

**Comment by paulh-aja** [comment]
QA tells me that a 17.0.1 release is slated for February. I don’t have a specific date yet.

You can wait for the official release to be tagged, use the ntv2_17_0 branch in its current pre-release state, or cherry-pick the changes you need. Note that AJA only provides support for officially tagged releases.

**Comment by paulh-aja** [comment]
@janbrothanek Have you verified that this is fixed for you if you use the latest ntv2_17_0 branch?

**Comment by janbrothanek** [comment]
@paulh-aja yes, I can confirm it's fixed. Thank you.

**Comment by loganb-aja** [comment]
Thanks for confirming @janbrothanek.

Closing...
